### ISSUE TITLE
Isn't http requests already async as web api?

### ISSUE THREAD

**Issue by 2013gang** [bcherny/angular-twerk#1]
Hi @bcherny, I wonder what the benefit is to make web worker to do the http request? Thanks

**Comment by bcherny** [comment]
Requests can be parallelized, but as I understand it, response deserialization happens in the main thread. For large non-streaming responses, this can be a long-lived operation that blocks the ui thread.

What I realized while working on twerk, is that to communicate between js threads the browser forces you to serialize all messages anyway (to avoid contention), so you'd have to re-serialize in your worker and re-deserialize in your main thread. So unless you're applying some heavy transformations to the response, making requests from a worker will probably just slow you down.

**Comment by 2013gang** [comment]
Thanks for answering. Maybe it could be put in the readme.
